# Generated by Django 3.1.5 on 2021-03-06 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20210305_1915'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profile',
            new_name='Userprofile',
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 15, 2, 36, 136889)),
        ),
    ]
